"""Generate the C weights header and test vectors for the MCU port of the
49-parameter event classifier. Emits mlp49_weights.h (weights +
standardization constants) and mlp49_test_vectors.h (32 inputs with
float64 numpy reference outputs). Run: python3 make_mcu_port.py"""
import json

import numpy as np

w = json.load(open("model_weights.json"))
W1 = np.array(w["W1"], np.float32); b1 = np.array(w["b1"], np.float32)
W2 = np.array(w["W2"], np.float32); b2 = np.array(w["b2"], np.float32)
mu = np.array(w["standardize_mean"], np.float32)
sd = np.array(w["standardize_std"], np.float32)

def carr(name, a):
    flat = np.asarray(a, np.float32).ravel()
    body = ", ".join(f"{v:.9g}f" for v in flat)
    return f"static const float {name}[{len(flat)}] = {{{body}}};\n"

with open("mlp49_weights.h", "w") as fh:
    fh.write("/* generated by make_mcu_port.py from model_weights.json */\n")
    fh.write("#define N_IN 4\n#define N_HID 8\n")
    fh.write(carr("MLP_W1", W1))   # row-major (in, hid)
    fh.write(carr("MLP_B1", b1))
    fh.write(carr("MLP_W2", W2))
    fh.write(carr("MLP_B2", b2))
    fh.write(carr("STD_MU", mu))
    fh.write(carr("STD_SD", sd))

rng = np.random.default_rng(42)
X = rng.normal(mu, sd, size=(32, 4)).astype(np.float32)
Xn = (X - mu) / sd
h = np.maximum(0.0, Xn @ W1 + b1)
y = 1.0 / (1.0 + np.exp(-(h @ W2 + b2))).ravel()
with open("mlp49_test_vectors.h", "w") as fh:
    fh.write("/* generated: raw-feature inputs + numpy reference outputs */\n")
    fh.write("#define N_TEST 32\n")
    fh.write(carr("TEST_X", X))
    fh.write(carr("TEST_Y", y))
print("wrote mlp49_weights.h, mlp49_test_vectors.h")
